# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.define "server" do |server|
    server.vm.box = "ubuntu/trusty64"
	server.vm.hostname = "netperf-server"
	server.vm.network "private_network", ip: "192.168.33.93"
	server.vm.provision "shell", inline: "sudo apt-get -y install netperf"
	server.vm.provision "shell", inline: "cp /vagrant/runall.sh /home/vagrant/"
	
	server.vm.provider "virtualbox" do |vb|
		vb.name = "vm-netperf-server"
		vb.memory = 2048
		vb.cpus = 2
	end
  end
  
  config.vm.define "client" do |client|
    client.vm.box = "ubuntu/trusty64"
	client.vm.hostname = "netperf-client"
	client.vm.network "private_network", ip: "192.168.33.94"
	client.vm.provision "hosts", sync_hosts: true
	client.vm.provision "shell", inline: "sudo apt-get -y install netperf"
	client.vm.provision "shell", inline: "cp /vagrant/runall.sh /home/vagrant/"
	
	client.vm.provider "virtualbox" do |vb|
		vb.name = "vm-netperf-client"
		vb.memory = 2048
		vb.cpus = 2
	end
  end
    
end
