# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "vm-mbw"
  config.vm.provision "shell", path: "provision.sh"
  config.vm.provision "shell", inline: "cp /vagrant/runall.sh /home/testing/"
  
  config.vm.provider "virtualbox" do |vb|
	vb.name = "vm-mbw"
    vb.memory = 4096
	vb.cpus = 2
  end
  
end
